#!/usr/bin/env python
# license removed for brevity
import rospy
from std_msgs.msg import String
import requests 


def talker():
    url = "http://127.0.0.1:5000/view"
    pub = rospy.Publisher('coffeeInfo', String, queue_size=10)
    rospy.init_node('talker', anonymous=True)
    # pub.publish(res.text)
    rate = rospy.Rate(0.1)
    test_str = ""
    while not rospy.is_shutdown():
        res = requests.get(url)
            # hello_str = "hello world %s" % rospy.get_time()
        rospy.loginfo(res.text)
        if test_str != res.text:
            test_str = res.text.strip()
            pub.publish(test_str)
        rate.sleep()

if __name__ == '__main__':
    try:
        talker()
    except rospy.ROSInterruptException:
        pass

